{
 "title": "Batch dashboard1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Число успешных запусков",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "spring_batch_job_seconds_count{spring_batch_job_status=\"COMPLETED\"}",
     "legendFormat": "Число успешных запусков"
    }
   ]
  },
  {
   "title": "Динамика времени обработки",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(spring_batch_job_seconds_sum{spring_batch_job_status=\"COMPLETED\"}[5m])",
     "legendFormat": "Время"
    },
    {
     "expr": "rate(spring_batch_job_seconds_count{spring_batch_job_status=\"COMPLETED\"}[5m])",
     "legendFormat": "Количество"
    }
   ]
  },
  {
   "title": "Среднее время успешного запуска",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_batch_job_seconds_sum{spring_batch_job_status=\"COMPLETED\"}",
     "legendFormat": "Общее время запусков"
    },
    {
     "expr": "spring_batch_job_seconds_count{spring_batch_job_status=\"COMPLETED\"}",
     "legendFormat": "Количество запусков"
    }
   ]
  },
  {
   "title": "Завершились с ошибками",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_batch_job_seconds_count{spring_batch_job_status=\"FAILED\"}",
     "legendFormat": "Завершилось с ошибками"
    }
   ]
  },
  {
   "title": "Динамика времени обработки",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(spring_batch_job_seconds_sum{spring_batch_job_status=\"FAILED\"}[5m])",
     "legendFormat": "Время"
    },
    {
     "expr": "rate(spring_batch_job_seconds_count{spring_batch_job_status=\"FAILED\"}[5m])",
     "legendFormat": "Количество"
    }
   ]
  }
 ]
}