apiVersion: batch/v1
kind: Job
metadata:
  name: my-test-job
spec:
  template:
    metadata: {}
    spec:
      containers:
      - name: my-test-job
        image: shipping-exporter:v1
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres-service:5432/analytics"
        resources: {}
      restartPolicy: Never
status: {}
