spring.application.name=tradeware-job-client
server.port=8081

# Включаем трейсинг на 100% запросов
management.tracing.sampling.probability=1.0

tradeware.batch-url=http://localhost:8080/run-job

management.zipkin.tracing.endpoint=
spring.zipkin.enabled=false