input {
	beats {
	    port => 5044			# Это стандартный "слухач" для протокола Lumberjack (то, на чем говорит Filebeat).
	    host => "0.0.0.0"		# Принимай соединения со всех сетевых интерфейсов внутри контейнера», а не только с localhost
  	}
}

output {
	elasticsearch {
		hosts => elasticsearch			# В Docker-сети Logstash будет искать сервис именно по имени elasticsearch
		manage_template => false		# Не пытайся сам создать схему данных (Mapping) в Elastic, пусть Filebeat или я вручную сделаем это
    	index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"		# Каждые сутки будет создаваться новый индекс
	}

     stdout { codec => rubydebug }		# Каждое событие, которое Logstash получил и обработал, он выведет в свою консоль
}