* ADR-0001: Реализация ETL-операций
  :PROPERTIES:
  :ID:       adr-0001
  :REFERS_TO_REQ: 
  :STATUS:   PROPOSED
  :DATE:     2026-03-23
  :END:

** Контекст
Сотрудники складов в конце рабочей смены загружают csv-отчеты об остатках.
При штатной нагрузке в момент обработки загруженных отчетов система работает стабильно.
Но в периоды пиковых нагрузок производительность системы значительно деградирует.

Это провоцирует финансовые и репутационные риски, так как:
- Существенно падает операционная эффективность сотрудников.
- Она приводит к просрочкам поставок и неэффективной логистике.
- На уровне клиентов из-за этого возникают цепные задержки в строительных процессах.

В ближайшее время ожидается существенный рост и базовой, и пиковой нагрузок.
Увеличится:
- число пользователей
- число заявок на хранение
- объемов данных по движениям 

Также:
- расширится номенклатура товаров
- потребуется интеграция с новыми источниками данных

** Технический анализ
Деградацию производительности при росте нагрузки вызывают:
- Отсутствие изоляции ресурсов:
    - Отчеты обрабатывает монолит
        - Процессы обработки конкурируют за CPU и RAM с основными бизнес-функциями и занимют общий пул потоков.
- Неэффективная работа с БД:
    - Данные вставляются построчно. Каждая из тысяч строк инициирует отдельную транзакцию.
        - Это перегружает транзакционный лог PostgreSQL и блокирует таблицы, делая базу недоступной для оперативных запросов.

** Проблема
Разработать архитектуру решения для ETL-операций и хранения данных, которая удовлетворяет следующим требованиям:

#+INCLUDE: "requirements.org::#all-reqs"

** Решение
Схемы
- C2.puml
- C3 dataflow-short.puml

Spring Batch - выбран для реализации логики обработки данных.
PostgreSQL - выбран для хранения промежуточных состояний Spring Batch (JobRepository).

*** Аргументация
Выбор Spring Batch обоснован [[adr-0002]]

Выбор PostgreSql для Spring Batch JobRepository оптимален, так как:
- закрывает требования по надежности
- соответствует текущему стеку
- соответствует облачной инфраструктуре

***** ✅ [[id:uq-001]] 
  :PROPERTIES:
  :TYPE: REQ_REALIZED
  :REFERS_TO_REQ: uq-001
  :END:
- *Элемент схемы:*
  - Монолит
- *Механизм реализации:*
  - Gatekeeper Pattern
- *Доказательство*
  - Делает первичную проверку формата, не пуская «мусор» в S3 и Воркер.

***** ✅ [[id:uq-002]]
  :PROPERTIES:
  :TYPE: REQ_REALIZED
  :REFERS_TO_REQ: uq-002
  :END:
- *Элемент схемы:*
  - Воркер и его связи
- *Механизм реализации:*
  - Step Persistence: retries, restartability
  - Performance: chunk processing, records skipping
  - Logic complexity: modular declaration of ETL steps 
- *Доказательство*
  - описание процесса глубокой валидации, обогащения и записи реализуется встроенными средствами Spring Batch

***** ✅ [[id:uq-003]] Мониторинг
  :PROPERTIES:
  :REFERS_TO_REQ: uq-003
  :TYPE: REQ_REALIZED
  :END:
- *Элемент схемы:*
  - Обратная связь Воркер-Монолит
- *Механизм реализации:*
  - Message queue
- *Доказательство*
  - Монолит подписан на сообщения о событиях обработки от воркера.
  - Монолит обновляет статус обработки отчета и использует текущие средства оповещения пользователей

***** ✅ [[id:req-nf-001]]
  :PROPERTIES:
  :REFERS_TO_REQ: req-nf-001
  :TYPE: REQ_REALIZED
  :END:
- *Элемент схемы:*
  - Воркер
- *Механизм реализации:*
  - Сhunk processing
- *Доказательство*
  - Воркер загржуает, обрабатывает и записывает данные пакетно средствами Spring Batch в сервисе, отдельном от монолита.

***** ✅ [[id:req-nf-002]] 
  :PROPERTIES:
  :REFERS_TO_REQ: req-nf-002
  :TYPE: REQ_REALIZED
  :END:
- *Элемент схемы:*
  - Монолит, GCP Pub/Sub, Воркер
- *Механизм реализации:*
  - Message queue, horizontal scaling, isolation
- *Доказательство*
  - задача монолита - только переложить файлы отчетов в хранилище. Нагрузка на него минимальна.
  - Воркер вынесен в отдельный сервис и ему выдаются независимые ресурсы для обеспечения производительности.
  - Добавление поднятых инстансов воркеров позволяет распределить поток отчетов для сохранения производительности под нагрузкой.
  - Монолит стреляет задачами на обработку через очередь
  - Монолит получает обратную связь о событиях в процессе обработки через очередь  

***** ✅ [[id:req-nf-003]] 
  :PROPERTIES:
  :REFERS_TO_REQ: req-nf-003
  :TYPE: REQ_REALIZED
  :END:
- *Элемент схемы:*
  - Монолит, GCP Pub/Sub, Воркер
- *Механизм реализации:*
  - Google Kubernetes Engine (GKE), GCP Pub/Sub, HPA (Horizontal Pod Autoscaler)
- *Доказательство*
  - в Google Cloud Platform можно настроить автоматическое масштабирование по количеству сообщений в очереди

***** ✅ [[id:req-nf-004]]
  :PROPERTIES:
  :REFERS_TO_REQ: req-nf-004
  :TYPE
  :END:
- *Элемент схемы:*
  - Воркер
- *Механизм реализации:*
  - Docker
- *Доказательство*
  - Является самостоятельным Java приложением, которое можно упаковать в Docker

***** ✅ [[id:req-nf-006]] 
  :PROPERTIES:
  :REFERS_TO_REQ: req-nf-006
  :TYPE: REQ_REALIZED
  :END:
- Реализуется средствами Spring Batch

***** ✅ [[id:req-nf-007]] 
  :PROPERTIES:
  :REFERS_TO_REQ: req-nf-007
  :TYPE: REQ_REALIZED
  :END:
- Реализуется средствами Spring Batch

***** ✅ [[id:req-nf-008]] 
  :PROPERTIES:
  :REFERS_TO_REQ: req-nf-008
  :TYPE: REQ_REALIZED
  :END:
- Частично реализуется средствами Spring Batch savepoints.